<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <groupId>org.dromara</groupId>
        <artifactId>ruoyi-modules</artifactId>
        <version>${revision}</version>
    </parent>

    <groupId>com.qihe</groupId>
    <artifactId>ruoyi-antflow</artifactId>
    <description>
        集成Ant flow工作流引擎
    </description>
    <properties>
        <maven.compiler.source>17</maven.compiler.source>
        <maven.compiler.target>17</maven.compiler.target>
        <antflow.version>0.110.0</antflow.version>
        <jodd-core.version>5.3.0</jodd-core.version>
        <jodd-servlet.version>6.0.0</jodd-servlet.version>
        <jodd-mail.version>7.1.0</jodd-mail.version>
        <jodd-util.version>6.3.0</jodd-util.version>
        <jodd-bean.version>5.1.6</jodd-bean.version>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
    </properties>
    <dependencies>
        <!-- jodd 配置 begin -->
<!--        <dependency>-->
<!--            <groupId>org.jodd</groupId>-->
<!--            <artifactId>jodd-core</artifactId>-->
<!--            <version>${jodd-core.version}</version>-->
<!--            <exclusions>-->
<!--                <exclusion>-->
<!--                    <groupId>org.jodd</groupId>-->
<!--                    <artifactId>jodd-util</artifactId>-->
<!--                </exclusion>-->
<!--            </exclusions>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>org.jodd</groupId>-->
<!--            <artifactId>jodd-servlet</artifactId>-->
<!--            <version>${jodd-servlet.version}</version>-->
<!--            <exclusions>-->
<!--                <exclusion>-->
<!--                    <groupId>org.jodd</groupId>-->
<!--                    <artifactId>jodd-core</artifactId>-->
<!--                </exclusion>-->
<!--            </exclusions>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>org.jodd</groupId>-->
<!--            <artifactId>jodd-util</artifactId>-->
<!--            <version>${jodd-util.version}</version>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>org.jodd</groupId>-->
<!--            <artifactId>jodd-mail</artifactId>-->
<!--            <version>${jodd-mail.version}</version>-->
<!--            <exclusions>-->
<!--                <exclusion>-->
<!--                    <groupId>org.jodd</groupId>-->
<!--                    <artifactId>jodd-util</artifactId>-->
<!--                </exclusion>-->
<!--            </exclusions>-->
<!--        </dependency>-->
<!--        <dependency>-->
<!--            <groupId>org.jodd</groupId>-->
<!--            <artifactId>jodd-bean</artifactId>-->
<!--            <version>${jodd-bean.version}</version>-->
<!--            <exclusions>-->
<!--                <exclusion>-->
<!--                    <groupId>org.jodd</groupId>-->
<!--                    <artifactId>jodd-core</artifactId>-->
<!--                </exclusion>-->
<!--            </exclusions>-->
<!--        </dependency>-->
        <!-- jodd 配置 end -->
<!--        <dependency>-->
<!--            <groupId>io.github.mrtylerzhou</groupId>-->
<!--            <artifactId>antflow-spring-boot-starter</artifactId>-->
<!--            <version>${antflow.version}</version>-->
<!--            <exclusions>-->
<!--                <exclusion>-->
<!--                    <groupId>com.thoughtworks.xstream</groupId>-->
<!--                    <artifactId>xstream</artifactId>-->
<!--                </exclusion>-->
<!--                <exclusion>-->
<!--                    <groupId>org.jodd</groupId>-->
<!--                    <artifactId>jodd-util</artifactId>-->
<!--                </exclusion>-->
<!--                <exclusion>-->
<!--                    <groupId>org.jodd</groupId>-->
<!--                    <artifactId>jodd-bean</artifactId>-->
<!--                </exclusion>-->
<!--                <exclusion>-->
<!--                    <groupId>org.jodd</groupId>-->
<!--                    <artifactId>jodd-mail</artifactId>-->
<!--                </exclusion>-->
<!--                <exclusion>-->
<!--                    <groupId>org.jodd</groupId>-->
<!--                    <artifactId>jodd-servlet</artifactId>-->
<!--                </exclusion>-->
<!--                <exclusion>-->
<!--                    <groupId>org.drools</groupId>-->
<!--                    <artifactId>drools-core</artifactId>-->
<!--                </exclusion>-->
<!--                <exclusion>-->
<!--                    <groupId>com.google.protobuf</groupId>-->
<!--                    <artifactId>protobuf-java</artifactId>-->
<!--                </exclusion>-->
<!--                <exclusion>-->
<!--                    <groupId>commons-io</groupId>-->
<!--                    <artifactId>commons-io</artifactId>-->
<!--                </exclusion>-->
<!--                <exclusion>-->
<!--                    <groupId>mysql</groupId>-->
<!--                    <artifactId>mysql-connector-java</artifactId>-->
<!--                </exclusion>-->
<!--                <exclusion>-->
<!--                    <groupId>com.baomidou</groupId>-->
<!--                    <artifactId>mybatis-plus-extension</artifactId>-->
<!--                </exclusion>-->
<!--                <exclusion>-->
<!--                    <groupId>org.mybatis.spring.boot</groupId>-->
<!--                    <artifactId>mybatis-spring-boot-starter</artifactId>-->
<!--                </exclusion>-->
<!--                <exclusion>-->
<!--                    <groupId>com.baomidou</groupId>-->
<!--                    <artifactId>mybatis-plus-boot-starter</artifactId>-->
<!--                </exclusion>-->
<!--                <exclusion>-->
<!--                    <groupId>com.google.guava</groupId>-->
<!--                    <artifactId>guava</artifactId>-->
<!--                </exclusion>-->
<!--            </exclusions>-->
<!--        </dependency>-->
        <dependency>
            <groupId>org.dromara</groupId>
            <artifactId>ruoyi-common-sse</artifactId>
        </dependency>

        <dependency>
            <groupId>org.dromara</groupId>
            <artifactId>ruoyi-common-doc</artifactId>
        </dependency>

        <dependency>
            <groupId>org.dromara</groupId>
            <artifactId>ruoyi-common-mail</artifactId>
        </dependency>

        <dependency>
            <groupId>org.dromara</groupId>
            <artifactId>ruoyi-common-sms</artifactId>
        </dependency>

        <dependency>
            <groupId>org.dromara</groupId>
            <artifactId>ruoyi-common-mybatis</artifactId>
        </dependency>
        <dependency>
            <groupId>org.dromara</groupId>
            <artifactId>ruoyi-common-web</artifactId>
        </dependency>
        <dependency>
            <groupId>org.dromara</groupId>
            <artifactId>ruoyi-common-log</artifactId>
        </dependency>
        <dependency>
            <groupId>org.dromara</groupId>
            <artifactId>ruoyi-common-idempotent</artifactId>
        </dependency>
        <dependency>
            <groupId>org.dromara</groupId>
            <artifactId>ruoyi-common-excel</artifactId>
        </dependency>
        <dependency>
            <groupId>org.dromara</groupId>
            <artifactId>ruoyi-common-translation</artifactId>
        </dependency>
        <dependency>
            <groupId>org.dromara</groupId>
            <artifactId>ruoyi-common-tenant</artifactId>
        </dependency>
        <dependency>
            <groupId>org.dromara</groupId>
            <artifactId>ruoyi-common-security</artifactId>
        </dependency>
        <dependency>
            <groupId>org.dromara.warm</groupId>
            <artifactId>warm-flow-mybatis-plus-sb3-starter</artifactId>
        </dependency>
        <dependency>
            <groupId>org.dromara.warm</groupId>
            <artifactId>warm-flow-plugin-ui-sb-web</artifactId>
        </dependency>
    </dependencies>
</project>
